/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://omgsrv1.meas.ncsu.edu:8080/thredds/catalog.xml -num 5 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/ncsu_meas >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://omgarch1.meas.ncsu.edu:8080/thredds/catalog/fmrc/sabgom/catalog.xml -num 5 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/ncsu_2 >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://omgsrv1.meas.ncsu.edu:8080/thredds/catalog/fmrc/us_east/catalog.xml -num 5 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/ncsu_east >> /tmp/ncISOAllProviders.log 2>&1

/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://crow.marine.usf.edu:8080/thredds/catalog.xml -num 1 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://crow.marine.usf.edu:8080/thredds/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://crow.marine.usf.edu:8080/thredds/catalog/WFS_ROMS_NF_model/catalog.html -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://crow.marine.usf.edu:8080/thredds/catalog/WFS_ROMS_NF_model/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usf >> /tmp/ncISOAllProviders.log 2>&1

/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/EastCoast/2D/NAM-FC/catalog.xml -num 3 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog.xml -num 1 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/waf/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog.xml -num 10 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/waf/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/EastCoast/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1

/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/EastCoast/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southwest/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southwest/2D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southeast/2D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southeast/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/NorthernGulf/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/NorthernGulf/2D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf >> /tmp/ncISOAllProviders.log 2>&1

/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://tds.secoora.org/thredds/catalog_hfradar.xml -num 1 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usc >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://tds.secoora.org/thredds/catalog_hfradar.xml -num 3 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usc >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://tds.secoora.org/thredds/catalog_platforms.xml -num 1 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usc >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://tds.secoora.org/thredds/catalog_platforms.xml -num 10 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usc >> /tmp/ncISOAllProviders.log 2>&1
/usr/lib/jvm/java-7-openjdk-i386/jre/bin/java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://tds.secoora.org/thredds/catalog.xml -num 3 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/usc >> /tmp/ncISOAllProviders.log 2>&1

/usr/bin/python /usr/local/userapps/secoora-portal/secoora/manage.py cswMaintain --UpdateMetadata --MetadataIniFile=/usr/local/userapps/secoora-portal/secoora/general/management/commands/metadata_file_list.ini
