java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/EastCoast/2D/NAM-FC/catalog.xml -num 3 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog.xml -num 1 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/waf/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog.xml -num 10 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/waf/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/EastCoast/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf

java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/EastCoast/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southwest/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southwest/2D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southeast/2D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/Southeast/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/NorthernGulf/3D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf
java -Xms1024m -Xmx1024m -jar ncISO-2.3.jar -custom true -xsl UnidataDD2MI.xsl -ts http://thredds.coastal.ufl.edu:8080/thredds/catalog/CH3D-SSMS/NorthernGulf/2D/NAM-FC/catalog.xml -num 2 -depth 20 -iso true -waf /usr/local/userapps/secoora-portal/metadata/xml/uf


/usr/bin/python /usr/local/userapps/secoora-portal/secoora/manage.py cswMaintain --UpdateMetadata --MetadataIniFile=/usr/local/userapps/secoora-portal/secoora/general/management/commands/uf_metadata_file_list.ini